"""Initial migration

Revision ID: 8cfdef7a7aeb
Revises: 322a22d8e450
Create Date: 2024-09-04 00:23:35.086657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cfdef7a7aeb'
down_revision = '322a22d8e450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sms_enabled')

    # ### end Alembic commands ###
